// <auto-generated />
using System;
using Application;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Application.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260220092606_RenameConstraints")]
    partial class RenameConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.TrackedEntryBase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)")
                        .HasColumnName("discriminator");

                    b.Property<TimeSpan>("Duration")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("interval")
                        .HasColumnName("duration")
                        .HasComputedColumnSql("end_time - start_time", true);

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("employee_id");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_time");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TimeZoneId")
                        .HasColumnType("text")
                        .HasColumnName("time_zone_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_tracked_entries");

                    b.ToTable("tracked_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_entries_end_time_is_greater_than_start_time", "\"end_time\" > \"start_time\"");

                            t.HasCheckConstraint("ck_entries_type_not_zero", "\"type\" <> 0");
                        });

                    b.HasDiscriminator().HasValue("TrackedEntryBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Core.Entities.TaskEntry", b =>
                {
                    b.HasBaseType("Core.Entities.TrackedEntryBase");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("task_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_entries_end_time_is_greater_than_start_time", "\"end_time\" > \"start_time\"");

                            t.HasCheckConstraint("ck_entries_type_not_zero", "\"type\" <> 0");
                        });

                    b.HasDiscriminator().HasValue("TaskEntry");
                });

            modelBuilder.Entity("Core.Entities.UnwellEntry", b =>
                {
                    b.HasBaseType("Core.Entities.TrackedEntryBase");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("ck_entries_end_time_is_greater_than_start_time", "\"end_time\" > \"start_time\"");

                            t.HasCheckConstraint("ck_entries_type_not_zero", "\"type\" <> 0");
                        });

                    b.HasDiscriminator().HasValue("UnwellEntry");
                });
#pragma warning restore 612, 618
        }
    }
}
