@authApiRootUrl = {{$processEnv AUTH_API_ROOT_URL}}
@apiRootUrl = {{$processEnv API_ROOT_URL}}
@authLogin = {{$processEnv AUTH_SLYTHERINE_TENANT_DRACO_MALFOY_LOGIN_WITH_ALL_PERMISSIONS}}

GET {{apiRootUrl}}/swagger/openapi.json

###

# @name login
POST {{authApiRootUrl}}/login

{
    "login": "{{authLogin}}"
}

###

@accessToken = {{login.response.body.accessToken.value}}

# @name createComment
GET {{apiRootUrl}}/tracking/entries?startDate=2026-03-09&endDate=2026-03-15
X-DEBUG-TOKEN: {{accessToken}}

###