name: Trigger js-client sync in UI

on:
  workflow_call:
    inputs:
      new-js-client-version:
        required: true
        type: string
      
jobs:
  trigger-js-client-sync-in-ui:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
        
      - name: Trigger sync-js-client-with-api workflow in ui
        # NOTE: quotes for commit_message not needed because toJson writes quotes automatically 
        run: |
          curl -X POST https://api.github.com/repos/TourmalineCore/inner-circle-time-ui/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -u ${{ secrets.INNER_CIRCLE_TIME_UI_TRIGGER_TOKEN }} \
          -d '{
          "event_type": "trigger-js-client-sync-in-ui",
          "client_payload": {
              "new_js_client_version": "${{ inputs.new-js-client-version }}",
              "commit_message": ${{ toJson(github.event.head_commit.message) }}
            }
          }'
